# Generated by Django 5.2.1 on 2025-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bkash', 'Bkash')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
